//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: fulfillment/v1/cluster_order_type.proto

//go:build !protoopaque

package fulfillmentv1

import (
	v1 "github.com/innabox/fulfillment-service/internal/api/shared/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents the overall state of the order.
type ClusterOrderState int32

const (
	// Unspecified indicates that the state is unknown.
	ClusterOrderState_CLUSTER_ORDER_STATE_UNSPECIFIED ClusterOrderState = 0
	// Indicates that the order isn't completelly fulfilled yet.
	ClusterOrderState_CLUSTER_ORDER_STATE_PROGRESSING ClusterOrderState = 1
	// Indicates indicates that the order has been successfully fulfilled.
	//
	// The details of the resulting cluster will be available in the `cluster` object indicated by the `status.cluster_id`
	// field.
	ClusterOrderState_CLUSTER_ORDER_STATE_FULFILLED ClusterOrderState = 2
	// Indicates that fulfillment of the order failed.
	ClusterOrderState_CLUSTER_ORDER_STATE_FAILED ClusterOrderState = 3
)

// Enum value maps for ClusterOrderState.
var (
	ClusterOrderState_name = map[int32]string{
		0: "CLUSTER_ORDER_STATE_UNSPECIFIED",
		1: "CLUSTER_ORDER_STATE_PROGRESSING",
		2: "CLUSTER_ORDER_STATE_FULFILLED",
		3: "CLUSTER_ORDER_STATE_FAILED",
	}
	ClusterOrderState_value = map[string]int32{
		"CLUSTER_ORDER_STATE_UNSPECIFIED": 0,
		"CLUSTER_ORDER_STATE_PROGRESSING": 1,
		"CLUSTER_ORDER_STATE_FULFILLED":   2,
		"CLUSTER_ORDER_STATE_FAILED":      3,
	}
)

func (x ClusterOrderState) Enum() *ClusterOrderState {
	p := new(ClusterOrderState)
	*p = x
	return p
}

func (x ClusterOrderState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterOrderState) Descriptor() protoreflect.EnumDescriptor {
	return file_fulfillment_v1_cluster_order_type_proto_enumTypes[0].Descriptor()
}

func (ClusterOrderState) Type() protoreflect.EnumType {
	return &file_fulfillment_v1_cluster_order_type_proto_enumTypes[0]
}

func (x ClusterOrderState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Types of conditions used to describe a cluster order.
type ClusterOrderConditionType int32

const (
	// Unspecified indicates that the condition unknown.
	//
	// This will never be appear in the `spec.conditions` field of a order.
	ClusterOrderConditionType_CLUSTER_ORDER_CONDITION_TYPE_UNSPECIFIED ClusterOrderConditionType = 0
	// Accepted indicates that the order has been accepted by the system.
	ClusterOrderConditionType_CLUSTER_ORDER_CONDITION_TYPE_ACCEPTED ClusterOrderConditionType = 1
	// Rejected indicates that the order has been rejected by the system, so no further processing will be fulfill it.
	ClusterOrderConditionType_CLUSTER_ORDER_CONDITION_TYPE_REJECTED ClusterOrderConditionType = 2
	// Canceled indicates that the order has been canceled by the user.
	ClusterOrderConditionType_CLUSTER_ORDER_CONDITION_TYPE_CANCELED ClusterOrderConditionType = 3
	// Fulfilled indicates that the order has been successfully fulfilled.
	//
	// The details of the resulting cluster will be available in the `cluster` object indicated by the `status.cluster_id`
	// field.
	ClusterOrderConditionType_CLUSTER_ORDER_CONDITION_TYPE_FULFILLED ClusterOrderConditionType = 4
	// Failed indicates that fulfillment of the order failed.
	//
	// Currently there are no sepcific `reason` values defined.
	ClusterOrderConditionType_CLUSTER_ORDER_CONDITION_TYPE_FAILED ClusterOrderConditionType = 5
)

// Enum value maps for ClusterOrderConditionType.
var (
	ClusterOrderConditionType_name = map[int32]string{
		0: "CLUSTER_ORDER_CONDITION_TYPE_UNSPECIFIED",
		1: "CLUSTER_ORDER_CONDITION_TYPE_ACCEPTED",
		2: "CLUSTER_ORDER_CONDITION_TYPE_REJECTED",
		3: "CLUSTER_ORDER_CONDITION_TYPE_CANCELED",
		4: "CLUSTER_ORDER_CONDITION_TYPE_FULFILLED",
		5: "CLUSTER_ORDER_CONDITION_TYPE_FAILED",
	}
	ClusterOrderConditionType_value = map[string]int32{
		"CLUSTER_ORDER_CONDITION_TYPE_UNSPECIFIED": 0,
		"CLUSTER_ORDER_CONDITION_TYPE_ACCEPTED":    1,
		"CLUSTER_ORDER_CONDITION_TYPE_REJECTED":    2,
		"CLUSTER_ORDER_CONDITION_TYPE_CANCELED":    3,
		"CLUSTER_ORDER_CONDITION_TYPE_FULFILLED":   4,
		"CLUSTER_ORDER_CONDITION_TYPE_FAILED":      5,
	}
)

func (x ClusterOrderConditionType) Enum() *ClusterOrderConditionType {
	p := new(ClusterOrderConditionType)
	*p = x
	return p
}

func (x ClusterOrderConditionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterOrderConditionType) Descriptor() protoreflect.EnumDescriptor {
	return file_fulfillment_v1_cluster_order_type_proto_enumTypes[1].Descriptor()
}

func (ClusterOrderConditionType) Type() protoreflect.EnumType {
	return &file_fulfillment_v1_cluster_order_type_proto_enumTypes[1]
}

func (x ClusterOrderConditionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Contains the details that the user provides to request the provisioning of a cluster, as well as the current status
// of the order provided by the system.
type ClusterOrder struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the order.
	//
	// This will be automatically generated by the system when the order is placed.
	Id            string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata      *v1.Metadata        `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *ClusterOrderSpec   `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *ClusterOrderStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterOrder) Reset() {
	*x = ClusterOrder{}
	mi := &file_fulfillment_v1_cluster_order_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOrder) ProtoMessage() {}

func (x *ClusterOrder) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_cluster_order_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ClusterOrder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterOrder) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClusterOrder) GetSpec() *ClusterOrderSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ClusterOrder) GetStatus() *ClusterOrderStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ClusterOrder) SetId(v string) {
	x.Id = v
}

func (x *ClusterOrder) SetMetadata(v *v1.Metadata) {
	x.Metadata = v
}

func (x *ClusterOrder) SetSpec(v *ClusterOrderSpec) {
	x.Spec = v
}

func (x *ClusterOrder) SetStatus(v *ClusterOrderStatus) {
	x.Status = v
}

func (x *ClusterOrder) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *ClusterOrder) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *ClusterOrder) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *ClusterOrder) ClearMetadata() {
	x.Metadata = nil
}

func (x *ClusterOrder) ClearSpec() {
	x.Spec = nil
}

func (x *ClusterOrder) ClearStatus() {
	x.Status = nil
}

type ClusterOrder_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the order.
	//
	// This will be automatically generated by the system when the order is placed.
	Id       string
	Metadata *v1.Metadata
	Spec     *ClusterOrderSpec
	Status   *ClusterOrderStatus
}

func (b0 ClusterOrder_builder) Build() *ClusterOrder {
	m0 := &ClusterOrder{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	x.Status = b.Status
	return m0
}

// Contains the details that the user provides to request the provisioning of the cluster.
type ClusterOrderSpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Reference to the cluster template.
	//
	// This is mandatory, and must be the value of the `id` field of one of the cluster templates.
	TemplateId string `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// Values of the template parameters.
	//
	// When using the HTTP+JSON version of the API the values must be represented as documented in the (ProtoJSON format
	// document)[https://protobuf.dev/programming-guides/json]. For example, if the template has a `number_of_nodes`
	// parameter of integer type, the complete order should be represented like this:
	//
	// ```json
	//
	//	{
	//	  "template_id": "123",
	//	  "template_parameters": {
	//	    "number_of_nodes": {
	//	      "@type": "type.googleapis.com/google.protobuf.Int32Value",
	//	      "value": 42
	//	    }
	//	  }
	//	}
	//
	// ```
	//
	// The possible values of the `@type` are the same as those used by the `type_url` field of the `Any` type:
	//
	// | Type                           | Value                                             |
	// |--------------------------------|---------------------------------------------------|
	// | Boolean                        | `type.googleapis.com/google.protobuf.BoolValue`   |
	// | Integer number, 32 bits        | `type.googleapis.com/google.protobuf.Int32Value`  |
	// | Integer number, 64 bits        | `type.googleapis.com/google.protobuf.Int64Value`  |
	// | Floating point number, 32 bits | `type.googleapis.com/google.protobuf.FloatValue`  |
	// | Floating point number, 64 bits | `type.googleapis.com/google.protobuf.DoubleValue` |
	// | String                         | `type.googleapis.com/google.protobuf.StringValue` |
	// | Timestamp                      | `type.googleapis.com/google.protobuf.Timestamp`   |
	// | Duration                       | `type.googleapis.com/google.protobuf.Duration`    |
	// | Array of bytes                 | `type.googleapis.com/google.protobuf.BytesValue`  |
	// | Any JSON value                 | `type.googleapis.com/google.protobuf.Value`       |
	TemplateParameters map[string]*anypb.Any `protobuf:"bytes,2,rep,name=template_parameters,json=templateParameters,proto3" json:"template_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClusterOrderSpec) Reset() {
	*x = ClusterOrderSpec{}
	mi := &file_fulfillment_v1_cluster_order_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterOrderSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOrderSpec) ProtoMessage() {}

func (x *ClusterOrderSpec) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_cluster_order_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ClusterOrderSpec) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *ClusterOrderSpec) GetTemplateParameters() map[string]*anypb.Any {
	if x != nil {
		return x.TemplateParameters
	}
	return nil
}

func (x *ClusterOrderSpec) SetTemplateId(v string) {
	x.TemplateId = v
}

func (x *ClusterOrderSpec) SetTemplateParameters(v map[string]*anypb.Any) {
	x.TemplateParameters = v
}

type ClusterOrderSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Reference to the cluster template.
	//
	// This is mandatory, and must be the value of the `id` field of one of the cluster templates.
	TemplateId string
	// Values of the template parameters.
	//
	// When using the HTTP+JSON version of the API the values must be represented as documented in the (ProtoJSON format
	// document)[https://protobuf.dev/programming-guides/json]. For example, if the template has a `number_of_nodes`
	// parameter of integer type, the complete order should be represented like this:
	//
	// ```json
	//
	//	{
	//	  "template_id": "123",
	//	  "template_parameters": {
	//	    "number_of_nodes": {
	//	      "@type": "type.googleapis.com/google.protobuf.Int32Value",
	//	      "value": 42
	//	    }
	//	  }
	//	}
	//
	// ```
	//
	// The possible values of the `@type` are the same as those used by the `type_url` field of the `Any` type:
	//
	// | Type                           | Value                                             |
	// |--------------------------------|---------------------------------------------------|
	// | Boolean                        | `type.googleapis.com/google.protobuf.BoolValue`   |
	// | Integer number, 32 bits        | `type.googleapis.com/google.protobuf.Int32Value`  |
	// | Integer number, 64 bits        | `type.googleapis.com/google.protobuf.Int64Value`  |
	// | Floating point number, 32 bits | `type.googleapis.com/google.protobuf.FloatValue`  |
	// | Floating point number, 64 bits | `type.googleapis.com/google.protobuf.DoubleValue` |
	// | String                         | `type.googleapis.com/google.protobuf.StringValue` |
	// | Timestamp                      | `type.googleapis.com/google.protobuf.Timestamp`   |
	// | Duration                       | `type.googleapis.com/google.protobuf.Duration`    |
	// | Array of bytes                 | `type.googleapis.com/google.protobuf.BytesValue`  |
	// | Any JSON value                 | `type.googleapis.com/google.protobuf.Value`       |
	TemplateParameters map[string]*anypb.Any
}

func (b0 ClusterOrderSpec_builder) Build() *ClusterOrderSpec {
	m0 := &ClusterOrderSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.TemplateId = b.TemplateId
	x.TemplateParameters = b.TemplateParameters
	return m0
}

// Contains the current status of the order.
type ClusterOrderStatus struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Indicates the overall state of the order.
	//
	// For more details check the conditions.
	State ClusterOrderState `protobuf:"varint,1,opt,name=state,proto3,enum=fulfillment.v1.ClusterOrderState" json:"state,omitempty"`
	// Contains a list of conditions that describe in detail the status of the order.
	//
	// For example, an order that failed could be represented like this (when converted to JSON):
	//
	//	{
	//	  "id": "123",
	//	  "spec": {
	//	    "template_id": "245"
	//	  },
	//	  "state": "CLUSTER_ORDER_STATE_FAILED",
	//	  "status": {
	//	    "conditions": [
	//	      {
	//	        "type: "CLUSTER_ORDER_CONDITION_TYPE_ACCEPTED",
	//	        "status": "CONDITION_STATUS_TRUE",
	//	        "last_transition_time": "2025-03-12 20:15:59+00:00",
	//	        "message": "The order has been automatically approved"
	//	      },
	//	      {
	//	        "type": "CLUSTER_ORDER_CONDITION_TYPE_FULFILLED",
	//	        "status": "CONDITION_STATUS_FALSE",
	//	        "last_transition_time": "2025-03-12 20:17:16+00:00"
	//	      },
	//	      {
	//	        "type": "CLUSTER_ORDER_CONDITION_TYPE_FAILED",
	//	        "status": "CONDITION_STATUS_TRUE",
	//	        "last_transition_time": "2025-03-12 20:18:59+00:00",
	//	        "reason": "DnsProvisioningFailure",
	//	        "message": "Failed to create DNS domain 'example.com' because it already exists"
	//	      }
	//	    ]
	//	  }
	//	}
	//
	// In this example the `ACCEPTED` condition is true. That tells us that the order was accepted, and the details tell
	// us that it was automatically approved.
	//
	// The `FUFILLED` condition isn't false. That means that order isn't fulfilled, without any other detail.
	//
	// The `FAILED` condition is true, so it is telling us that the fulfillment failed. It also gives additional detail
	// in the with both a _reason_ intended for use by programs, and some some details to help humans understand and debug
	// the issue.
	//
	// Note that in this example, to make it shorter, only three conditions appear. In general all the conditions (except
	// `UNPSECIFIED`) will appear exactly once.
	//
	// Note also that this is just an example, in particular the `DnsProvisioningFailure` reason for the failed condition
	// is imaginary. Check the documentation of the values of the `ClusterOrderConditionType` enumerated type to see
	// possible values for the reason.
	Conditions []*ClusterOrderCondition `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	// Reference to the resulting cluster.
	//
	// This will be automatically populated by the system when the requested cluster is completely provisoned. Further
	// details about the cluster, like the API URL, will be available in the corresponding `Cluster` object.
	ClusterId     string `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterOrderStatus) Reset() {
	*x = ClusterOrderStatus{}
	mi := &file_fulfillment_v1_cluster_order_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterOrderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOrderStatus) ProtoMessage() {}

func (x *ClusterOrderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_cluster_order_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ClusterOrderStatus) GetState() ClusterOrderState {
	if x != nil {
		return x.State
	}
	return ClusterOrderState_CLUSTER_ORDER_STATE_UNSPECIFIED
}

func (x *ClusterOrderStatus) GetConditions() []*ClusterOrderCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *ClusterOrderStatus) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterOrderStatus) SetState(v ClusterOrderState) {
	x.State = v
}

func (x *ClusterOrderStatus) SetConditions(v []*ClusterOrderCondition) {
	x.Conditions = v
}

func (x *ClusterOrderStatus) SetClusterId(v string) {
	x.ClusterId = v
}

type ClusterOrderStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Indicates the overall state of the order.
	//
	// For more details check the conditions.
	State ClusterOrderState
	// Contains a list of conditions that describe in detail the status of the order.
	//
	// For example, an order that failed could be represented like this (when converted to JSON):
	//
	//	{
	//	  "id": "123",
	//	  "spec": {
	//	    "template_id": "245"
	//	  },
	//	  "state": "CLUSTER_ORDER_STATE_FAILED",
	//	  "status": {
	//	    "conditions": [
	//	      {
	//	        "type: "CLUSTER_ORDER_CONDITION_TYPE_ACCEPTED",
	//	        "status": "CONDITION_STATUS_TRUE",
	//	        "last_transition_time": "2025-03-12 20:15:59+00:00",
	//	        "message": "The order has been automatically approved"
	//	      },
	//	      {
	//	        "type": "CLUSTER_ORDER_CONDITION_TYPE_FULFILLED",
	//	        "status": "CONDITION_STATUS_FALSE",
	//	        "last_transition_time": "2025-03-12 20:17:16+00:00"
	//	      },
	//	      {
	//	        "type": "CLUSTER_ORDER_CONDITION_TYPE_FAILED",
	//	        "status": "CONDITION_STATUS_TRUE",
	//	        "last_transition_time": "2025-03-12 20:18:59+00:00",
	//	        "reason": "DnsProvisioningFailure",
	//	        "message": "Failed to create DNS domain 'example.com' because it already exists"
	//	      }
	//	    ]
	//	  }
	//	}
	//
	// In this example the `ACCEPTED` condition is true. That tells us that the order was accepted, and the details tell
	// us that it was automatically approved.
	//
	// The `FUFILLED` condition isn't false. That means that order isn't fulfilled, without any other detail.
	//
	// The `FAILED` condition is true, so it is telling us that the fulfillment failed. It also gives additional detail
	// in the with both a _reason_ intended for use by programs, and some some details to help humans understand and debug
	// the issue.
	//
	// Note that in this example, to make it shorter, only three conditions appear. In general all the conditions (except
	// `UNPSECIFIED`) will appear exactly once.
	//
	// Note also that this is just an example, in particular the `DnsProvisioningFailure` reason for the failed condition
	// is imaginary. Check the documentation of the values of the `ClusterOrderConditionType` enumerated type to see
	// possible values for the reason.
	Conditions []*ClusterOrderCondition
	// Reference to the resulting cluster.
	//
	// This will be automatically populated by the system when the requested cluster is completely provisoned. Further
	// details about the cluster, like the API URL, will be available in the corresponding `Cluster` object.
	ClusterId string
}

func (b0 ClusterOrderStatus_builder) Build() *ClusterOrderStatus {
	m0 := &ClusterOrderStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.State = b.State
	x.Conditions = b.Conditions
	x.ClusterId = b.ClusterId
	return m0
}

// Contains the details of a condition that describes the status of a cluster order.
type ClusterOrderCondition struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Indicates the type of condition.
	Type ClusterOrderConditionType `protobuf:"varint,1,opt,name=type,proto3,enum=fulfillment.v1.ClusterOrderConditionType" json:"type,omitempty"`
	// Indicates status of the condition.
	Status v1.ConditionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=shared.v1.ConditionStatus" json:"status,omitempty"`
	// This time is the last time that the condition was updated.
	LastTransitionTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_transition_time,json=lastTransitionTime,proto3" json:"last_transition_time,omitempty"`
	// Contains a the reason of the condition in a format suitable for use by programs.
	//
	// The possible are documented in the `ClusterOrderConditionType` object.
	Reason *string `protobuf:"bytes,4,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	// Contains a text giving more details of the condition. This will usually be progress reports, or error messages, and
	// are intended for use by humans, to debug problems.
	Message       *string `protobuf:"bytes,5,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterOrderCondition) Reset() {
	*x = ClusterOrderCondition{}
	mi := &file_fulfillment_v1_cluster_order_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterOrderCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOrderCondition) ProtoMessage() {}

func (x *ClusterOrderCondition) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_cluster_order_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ClusterOrderCondition) GetType() ClusterOrderConditionType {
	if x != nil {
		return x.Type
	}
	return ClusterOrderConditionType_CLUSTER_ORDER_CONDITION_TYPE_UNSPECIFIED
}

func (x *ClusterOrderCondition) GetStatus() v1.ConditionStatus {
	if x != nil {
		return x.Status
	}
	return v1.ConditionStatus(0)
}

func (x *ClusterOrderCondition) GetLastTransitionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTransitionTime
	}
	return nil
}

func (x *ClusterOrderCondition) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *ClusterOrderCondition) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ClusterOrderCondition) SetType(v ClusterOrderConditionType) {
	x.Type = v
}

func (x *ClusterOrderCondition) SetStatus(v v1.ConditionStatus) {
	x.Status = v
}

func (x *ClusterOrderCondition) SetLastTransitionTime(v *timestamppb.Timestamp) {
	x.LastTransitionTime = v
}

func (x *ClusterOrderCondition) SetReason(v string) {
	x.Reason = &v
}

func (x *ClusterOrderCondition) SetMessage(v string) {
	x.Message = &v
}

func (x *ClusterOrderCondition) HasLastTransitionTime() bool {
	if x == nil {
		return false
	}
	return x.LastTransitionTime != nil
}

func (x *ClusterOrderCondition) HasReason() bool {
	if x == nil {
		return false
	}
	return x.Reason != nil
}

func (x *ClusterOrderCondition) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.Message != nil
}

func (x *ClusterOrderCondition) ClearLastTransitionTime() {
	x.LastTransitionTime = nil
}

func (x *ClusterOrderCondition) ClearReason() {
	x.Reason = nil
}

func (x *ClusterOrderCondition) ClearMessage() {
	x.Message = nil
}

type ClusterOrderCondition_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Indicates the type of condition.
	Type ClusterOrderConditionType
	// Indicates status of the condition.
	Status v1.ConditionStatus
	// This time is the last time that the condition was updated.
	LastTransitionTime *timestamppb.Timestamp
	// Contains a the reason of the condition in a format suitable for use by programs.
	//
	// The possible are documented in the `ClusterOrderConditionType` object.
	Reason *string
	// Contains a text giving more details of the condition. This will usually be progress reports, or error messages, and
	// are intended for use by humans, to debug problems.
	Message *string
}

func (b0 ClusterOrderCondition_builder) Build() *ClusterOrderCondition {
	m0 := &ClusterOrderCondition{}
	b, x := &b0, m0
	_, _ = b, x
	x.Type = b.Type
	x.Status = b.Status
	x.LastTransitionTime = b.LastTransitionTime
	x.Reason = b.Reason
	x.Message = b.Message
	return m0
}

var File_fulfillment_v1_cluster_order_type_proto protoreflect.FileDescriptor

var file_fulfillment_v1_cluster_order_type_proto_rawDesc = string([]byte{
	0x0a, 0x27, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x66, 0x75, 0x6c, 0x66, 0x69,
	0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x25, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc1, 0x01, 0x0a, 0x0c,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a,
	0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x66, 0x75,
	0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73,
	0x70, 0x65, 0x63, 0x12, 0x3a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0xfb, 0x01, 0x0a, 0x10, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x53, 0x70, 0x65, 0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x69, 0x0a, 0x13, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x38, 0x2e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x53, 0x70, 0x65, 0x63, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x12, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x1a, 0x5b, 0x0a, 0x17, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xb3, 0x01,
	0x0a, 0x12, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x37, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x45, 0x0a,
	0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x49, 0x64, 0x22, 0xab, 0x02, 0x0a, 0x15, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x66, 0x75,
	0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x4c, 0x0a, 0x14, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x12, 0x6c, 0x61, 0x73, 0x74,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2a, 0xa0, 0x01, 0x0a, 0x11, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x1f, 0x43, 0x4c, 0x55, 0x53, 0x54,
	0x45, 0x52, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x23, 0x0a, 0x1f,
	0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x10,
	0x01, 0x12, 0x21, 0x0a, 0x1d, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x4f, 0x52, 0x44,
	0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x55, 0x4c, 0x46, 0x49, 0x4c, 0x4c,
	0x45, 0x44, 0x10, 0x02, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f,
	0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c,
	0x45, 0x44, 0x10, 0x03, 0x2a, 0x9f, 0x02, 0x0a, 0x19, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x2c, 0x0a, 0x28, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x4f, 0x52,
	0x44, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x29, 0x0a, 0x25, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x4f, 0x52, 0x44, 0x45,
	0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x29, 0x0a, 0x25, 0x43,
	0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e,
	0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x4a, 0x45,
	0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x29, 0x0a, 0x25, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45,
	0x52, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x45, 0x44, 0x10,
	0x03, 0x12, 0x2a, 0x0a, 0x26, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x4f, 0x52, 0x44,
	0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x46, 0x55, 0x4c, 0x46, 0x49, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x27, 0x0a,
	0x23, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x43,
	0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x41,
	0x49, 0x4c, 0x45, 0x44, 0x10, 0x05, 0x42, 0xd6, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x66,
	0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x42, 0x15, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x6e, 0x61, 0x62, 0x6f, 0x78, 0x2f, 0x66, 0x75, 0x6c, 0x66, 0x69,
	0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x75, 0x6c, 0x66,
	0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x66, 0x75, 0x6c, 0x66, 0x69,
	0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x46, 0x58, 0x58, 0xaa, 0x02,
	0x0e, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x31, 0xca,
	0x02, 0x0e, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x5c, 0x56, 0x31,
	0xe2, 0x02, 0x1a, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x5c, 0x56,
	0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0f,
	0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_fulfillment_v1_cluster_order_type_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fulfillment_v1_cluster_order_type_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fulfillment_v1_cluster_order_type_proto_goTypes = []any{
	(ClusterOrderState)(0),         // 0: fulfillment.v1.ClusterOrderState
	(ClusterOrderConditionType)(0), // 1: fulfillment.v1.ClusterOrderConditionType
	(*ClusterOrder)(nil),           // 2: fulfillment.v1.ClusterOrder
	(*ClusterOrderSpec)(nil),       // 3: fulfillment.v1.ClusterOrderSpec
	(*ClusterOrderStatus)(nil),     // 4: fulfillment.v1.ClusterOrderStatus
	(*ClusterOrderCondition)(nil),  // 5: fulfillment.v1.ClusterOrderCondition
	nil,                            // 6: fulfillment.v1.ClusterOrderSpec.TemplateParametersEntry
	(*v1.Metadata)(nil),            // 7: shared.v1.Metadata
	(v1.ConditionStatus)(0),        // 8: shared.v1.ConditionStatus
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
	(*anypb.Any)(nil),              // 10: google.protobuf.Any
}
var file_fulfillment_v1_cluster_order_type_proto_depIdxs = []int32{
	7,  // 0: fulfillment.v1.ClusterOrder.metadata:type_name -> shared.v1.Metadata
	3,  // 1: fulfillment.v1.ClusterOrder.spec:type_name -> fulfillment.v1.ClusterOrderSpec
	4,  // 2: fulfillment.v1.ClusterOrder.status:type_name -> fulfillment.v1.ClusterOrderStatus
	6,  // 3: fulfillment.v1.ClusterOrderSpec.template_parameters:type_name -> fulfillment.v1.ClusterOrderSpec.TemplateParametersEntry
	0,  // 4: fulfillment.v1.ClusterOrderStatus.state:type_name -> fulfillment.v1.ClusterOrderState
	5,  // 5: fulfillment.v1.ClusterOrderStatus.conditions:type_name -> fulfillment.v1.ClusterOrderCondition
	1,  // 6: fulfillment.v1.ClusterOrderCondition.type:type_name -> fulfillment.v1.ClusterOrderConditionType
	8,  // 7: fulfillment.v1.ClusterOrderCondition.status:type_name -> shared.v1.ConditionStatus
	9,  // 8: fulfillment.v1.ClusterOrderCondition.last_transition_time:type_name -> google.protobuf.Timestamp
	10, // 9: fulfillment.v1.ClusterOrderSpec.TemplateParametersEntry.value:type_name -> google.protobuf.Any
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_fulfillment_v1_cluster_order_type_proto_init() }
func file_fulfillment_v1_cluster_order_type_proto_init() {
	if File_fulfillment_v1_cluster_order_type_proto != nil {
		return
	}
	file_fulfillment_v1_cluster_order_type_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fulfillment_v1_cluster_order_type_proto_rawDesc), len(file_fulfillment_v1_cluster_order_type_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fulfillment_v1_cluster_order_type_proto_goTypes,
		DependencyIndexes: file_fulfillment_v1_cluster_order_type_proto_depIdxs,
		EnumInfos:         file_fulfillment_v1_cluster_order_type_proto_enumTypes,
		MessageInfos:      file_fulfillment_v1_cluster_order_type_proto_msgTypes,
	}.Build()
	File_fulfillment_v1_cluster_order_type_proto = out.File
	file_fulfillment_v1_cluster_order_type_proto_goTypes = nil
	file_fulfillment_v1_cluster_order_type_proto_depIdxs = nil
}
