//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: fulfillment/v1/cluster_orders_service.proto

package fulfillmentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterOrders_List_FullMethodName   = "/fulfillment.v1.ClusterOrders/List"
	ClusterOrders_Get_FullMethodName    = "/fulfillment.v1.ClusterOrders/Get"
	ClusterOrders_Create_FullMethodName = "/fulfillment.v1.ClusterOrders/Create"
	ClusterOrders_Update_FullMethodName = "/fulfillment.v1.ClusterOrders/Update"
	ClusterOrders_Delete_FullMethodName = "/fulfillment.v1.ClusterOrders/Delete"
)

// ClusterOrdersClient is the client API for ClusterOrders service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterOrdersClient interface {
	// Retrieves the list of cluster orders.
	List(ctx context.Context, in *ClusterOrdersListRequest, opts ...grpc.CallOption) (*ClusterOrdersListResponse, error)
	// Retrieves the details of one specific cluster order.
	Get(ctx context.Context, in *ClusterOrdersGetRequest, opts ...grpc.CallOption) (*ClusterOrdersGetResponse, error)
	// Creates a new cluster order.
	Create(ctx context.Context, in *ClusterOrdersCreateRequest, opts ...grpc.CallOption) (*ClusterOrdersCreateResponse, error)
	// Updates an existing cluster order.
	//
	// In the HTTP+JSON version of the API this is mapped to the `PATCH` verb and the `update_mask` field is automatically
	// populated from the list of fields present in the request body. For example, to update the `state` of an order to
	// `FULFILLED` the request line should be like this:
	//
	// ```http
	// PATCH /api/fulfillment/v1/cluster_orders/123
	// ```
	//
	// And the request body should be like this:
	//
	// ```json
	//
	//	{
	//	  "status": {
	//	    "state": "CLUSTER_ORDER_STATE_FULFILLED"
	//	  }
	//	}
	//
	// ```
	//
	// The response body will contain the modified object.
	Update(ctx context.Context, in *ClusterOrdersUpdateRequest, opts ...grpc.CallOption) (*ClusterOrdersUpdateResponse, error)
	// Delete a cluster order.
	Delete(ctx context.Context, in *ClusterOrdersDeleteRequest, opts ...grpc.CallOption) (*ClusterOrdersDeleteResponse, error)
}

type clusterOrdersClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterOrdersClient(cc grpc.ClientConnInterface) ClusterOrdersClient {
	return &clusterOrdersClient{cc}
}

func (c *clusterOrdersClient) List(ctx context.Context, in *ClusterOrdersListRequest, opts ...grpc.CallOption) (*ClusterOrdersListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterOrdersListResponse)
	err := c.cc.Invoke(ctx, ClusterOrders_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterOrdersClient) Get(ctx context.Context, in *ClusterOrdersGetRequest, opts ...grpc.CallOption) (*ClusterOrdersGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterOrdersGetResponse)
	err := c.cc.Invoke(ctx, ClusterOrders_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterOrdersClient) Create(ctx context.Context, in *ClusterOrdersCreateRequest, opts ...grpc.CallOption) (*ClusterOrdersCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterOrdersCreateResponse)
	err := c.cc.Invoke(ctx, ClusterOrders_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterOrdersClient) Update(ctx context.Context, in *ClusterOrdersUpdateRequest, opts ...grpc.CallOption) (*ClusterOrdersUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterOrdersUpdateResponse)
	err := c.cc.Invoke(ctx, ClusterOrders_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterOrdersClient) Delete(ctx context.Context, in *ClusterOrdersDeleteRequest, opts ...grpc.CallOption) (*ClusterOrdersDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterOrdersDeleteResponse)
	err := c.cc.Invoke(ctx, ClusterOrders_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterOrdersServer is the server API for ClusterOrders service.
// All implementations must embed UnimplementedClusterOrdersServer
// for forward compatibility.
type ClusterOrdersServer interface {
	// Retrieves the list of cluster orders.
	List(context.Context, *ClusterOrdersListRequest) (*ClusterOrdersListResponse, error)
	// Retrieves the details of one specific cluster order.
	Get(context.Context, *ClusterOrdersGetRequest) (*ClusterOrdersGetResponse, error)
	// Creates a new cluster order.
	Create(context.Context, *ClusterOrdersCreateRequest) (*ClusterOrdersCreateResponse, error)
	// Updates an existing cluster order.
	//
	// In the HTTP+JSON version of the API this is mapped to the `PATCH` verb and the `update_mask` field is automatically
	// populated from the list of fields present in the request body. For example, to update the `state` of an order to
	// `FULFILLED` the request line should be like this:
	//
	// ```http
	// PATCH /api/fulfillment/v1/cluster_orders/123
	// ```
	//
	// And the request body should be like this:
	//
	// ```json
	//
	//	{
	//	  "status": {
	//	    "state": "CLUSTER_ORDER_STATE_FULFILLED"
	//	  }
	//	}
	//
	// ```
	//
	// The response body will contain the modified object.
	Update(context.Context, *ClusterOrdersUpdateRequest) (*ClusterOrdersUpdateResponse, error)
	// Delete a cluster order.
	Delete(context.Context, *ClusterOrdersDeleteRequest) (*ClusterOrdersDeleteResponse, error)
	mustEmbedUnimplementedClusterOrdersServer()
}

// UnimplementedClusterOrdersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterOrdersServer struct{}

func (UnimplementedClusterOrdersServer) List(context.Context, *ClusterOrdersListRequest) (*ClusterOrdersListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedClusterOrdersServer) Get(context.Context, *ClusterOrdersGetRequest) (*ClusterOrdersGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedClusterOrdersServer) Create(context.Context, *ClusterOrdersCreateRequest) (*ClusterOrdersCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedClusterOrdersServer) Update(context.Context, *ClusterOrdersUpdateRequest) (*ClusterOrdersUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedClusterOrdersServer) Delete(context.Context, *ClusterOrdersDeleteRequest) (*ClusterOrdersDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedClusterOrdersServer) mustEmbedUnimplementedClusterOrdersServer() {}
func (UnimplementedClusterOrdersServer) testEmbeddedByValue()                       {}

// UnsafeClusterOrdersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterOrdersServer will
// result in compilation errors.
type UnsafeClusterOrdersServer interface {
	mustEmbedUnimplementedClusterOrdersServer()
}

func RegisterClusterOrdersServer(s grpc.ServiceRegistrar, srv ClusterOrdersServer) {
	// If the following call pancis, it indicates UnimplementedClusterOrdersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterOrders_ServiceDesc, srv)
}

func _ClusterOrders_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterOrdersListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterOrdersServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterOrders_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterOrdersServer).List(ctx, req.(*ClusterOrdersListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterOrders_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterOrdersGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterOrdersServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterOrders_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterOrdersServer).Get(ctx, req.(*ClusterOrdersGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterOrders_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterOrdersCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterOrdersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterOrders_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterOrdersServer).Create(ctx, req.(*ClusterOrdersCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterOrders_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterOrdersUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterOrdersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterOrders_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterOrdersServer).Update(ctx, req.(*ClusterOrdersUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterOrders_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterOrdersDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterOrdersServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterOrders_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterOrdersServer).Delete(ctx, req.(*ClusterOrdersDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterOrders_ServiceDesc is the grpc.ServiceDesc for ClusterOrders service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterOrders_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fulfillment.v1.ClusterOrders",
	HandlerType: (*ClusterOrdersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ClusterOrders_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ClusterOrders_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ClusterOrders_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ClusterOrders_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ClusterOrders_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fulfillment/v1/cluster_orders_service.proto",
}
